data "google_firebase_web_app_config" "default" {
  provider   = google-beta
  project    = var.gcp_project_id
  web_app_id = google_firebase_web_app.default.app_id
}

output "firebase_config" {
  value = {
    apiKey            = data.google_firebase_web_app_config.default.api_key
    authDomain        = data.google_firebase_web_app_config.default.auth_domain
    projectId         = var.gcp_project_id
    storageBucket     = data.google_firebase_web_app_config.default.storage_bucket
    messagingSenderId = data.google_firebase_web_app_config.default.messaging_sender_id
    appId             = google_firebase_web_app.default.app_id
  }
  description = "Firebase Web App configuration parameters to be used in React/Next.js frontend"
  sensitive   = true
}

output "env_local_template" {
  value = <<EOT
# ===================================================================
# satorun.dev .env.local Template (Generated by Terraform)
# ===================================================================
NEXT_PUBLIC_FIREBASE_API_KEY="${data.google_firebase_web_app_config.default.api_key}"
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="${data.google_firebase_web_app_config.default.auth_domain}"
NEXT_PUBLIC_FIREBASE_PROJECT_ID="${var.gcp_project_id}"
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="${data.google_firebase_web_app_config.default.storage_bucket}"
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="${data.google_firebase_web_app_config.default.messaging_sender_id}"
NEXT_PUBLIC_FIREBASE_APP_ID="${google_firebase_web_app.default.app_id}"
EOT
  description = "A formatted block that you can directly copy-paste into .env.local"
}
